// DOM for the test case suite
const titleElement = document.createElement("title");
titleElement.innerHTML = "Calculator";
document.body.appendChild(titleElement);
const h1Element = document.createElement("h1");
h1Element.setAttribute("id", "title");
h1Element.innerText = "Task 9";
document.body.appendChild(h1Element);
const paraElement = document.createElement("p");
paraElement.setAttribute("id", "description");
paraElement.innerText = "A calculator has been created using HTML,CSS, JS dom manipulation and Bootstrap";
document.body.appendChild(paraElement);

//div
const divContainer = document.createElement("div");
divContainer.className = "div-container";
document.body.appendChild(divContainer);
// Input buttons
const inputElement = document.createElement("input");
inputElement.type = "number";
inputElement.placeholder = "0";
const btn1 = document.createElement("button");
btn1.innerText = "C";
const btn2 = document.createElement("button");
btn2.innerText = "<--";
const btn3 = document.createElement("button");
btn3.innerText = ".";
const btn4 = document.createElement("button");
btn4.innerText = "X";
const btn5 = document.createElement("button");
btn5.innerText = "7";
const btn6 = document.createElement("button");
btn6.innerText = "8";
const btn7 = document.createElement("button");
btn7.innerText = "9";
const btn8 = document.createElement("button");
btn8.innerText = "/";
const btn9 = document.createElement("button");
btn9.innerText = "4";
const btn10 = document.createElement("button");
btn10.innerText = "5";
const btn11= document.createElement("button");
btn11.innerText = "6";
const btn12 = document.createElement("button");
btn12.innerText = "-";
const btn13 = document.createElement("button");
btn13.innerText = "1";
const btn14 = document.createElement("button");
btn14.innerText = "2";
const btn15 = document.createElement("button");
btn15.innerText = "3";
const btn16 = document.createElement("button");
btn16.innerText = "+";
const btn17 = document.createElement("button");
btn17.innerText = "0";
const btn18 = document.createElement("button");
btn18.innerText = "00";
const btn19 = document.createElement("button");
btn19.innerText = "=";
divContainer.append(inputElement, btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, btn10, btn11, btn12, btn13, btn14, btn15, btn16, btn17, btn18, btn19);
